Create beta version webSocket
BinaryStudioAcademy/bsa-2021-mindbridge pull request #10
Opened 2021-08-02 10:17 UTC by GGrify

2021-08-03 07:57 UTC, kopot-o-d reviewed
Remove unnecessary comments (or add a reason why they are here), remove mention of 'localhost', there must be only route like '/data/hello' and host must be resolved in the proxy file

2021-08-03 12:03 UTC, Quipex requested changes
Merge with the latest dev to trigger auto-linter

2021-08-04 08:33 UTC, kopot-o-d approved these changes

2021-08-04 10:07 UTC, kopot-o-d approved these changes

2021-08-04 10:08 UTC, kopot-o-d approved these changes

2021-08-04 10:08 UTC, merged