Patch/add title to the pages
BinaryStudioAcademy/bsa-2021-mindbridge pull request #230
Opened 2021-09-08 19:36 UTC by Cooplix

2021-09-08 19:59 UTC, Quipex approved these changes

2021-09-08 20:02 UTC, Quipex requested changes

2021-09-08 20:02 UTC, Quipex commented on frontend/src/components/NotFoundContetn/index.tsx
> +      Seems like there are no result...
why?

2021-09-09 13:27 UTC, quipex-binary-studio approved these changes

2021-09-09 13:28 UTC, merged