Feature/create login page
BinaryStudioAcademy/bsa-2021-mindbridge pull request #4
Opened 2021-07-30 19:16 UTC by GGrify

2021-08-01 14:54 UTC, Quipex commented
Run eslint --fix against all files you've commited

2021-08-01 15:07 UTC, Quipex requested changes
When you're creating new reusable components like buttons, modals, icons, etc. Tend to make them separate components so that others can use them

2021-08-01 15:07 UTC, Quipex commented on frontend/src/screens/Login/components/LoginForm/index.tsx
> +    const svgButton = document.getElementById('viewButton');
Try not to use dom api directly when you're working with React

2021-08-01 15:07 UTC, Quipex commented on frontend/src/screens/Login/components/LoginForm/index.tsx
> +          '            </svg>';
Extract the custom input with hiding password to a separate reusable component

2021-08-02 16:38 UTC, AlenaGavriluk reviewed
There is no need to use {} with attributes values e.g. placeholder={"Enter your email"}
RegistrationForm/index.tsx and LoginForm/index.tsx  should be formatted with tabs.
<label htmlFor={"name"}>Name</label>
        <input id={"name"} type="text" placeholder={"Enter your name"} required/>
 <label htmlFor={"surname"}>Surname</label>

2021-08-03 08:04 UTC, kopot-o-d commented on frontend/src/screens/Login/components/HideSvg/index.tsx
> +
u don't need interfaces and mapState.. mapDispatch... for dull components, u can just remove all unnecessary constructions

2021-08-03 08:04 UTC, kopot-o-d commented on frontend/src/screens/Login/components/UnhideSvg/index.tsx
> +
u don't need interfaces and mapState.. mapDispatch... for dull components, u can just remove all unnecessary constructions

2021-08-03 08:05 UTC, kopot-o-d reviewed
move ALL SVGs to separate components

2021-08-03 08:16 UTC, GGrify commented
> There is no need to use {} with attributes values e.g. placeholder={"Enter your email"}
> RegistrationForm/index.tsx and LoginForm/index.tsx should be formatted with tabs.
> <label htmlFor={"name"}>Name
> <input id={"name"} type="text" placeholder={"Enter your name"} required/>
> <label htmlFor={"surname"}>Surname

2021-08-03 08:17 UTC, GGrify commented
> There is no need to use {} with attributes values e.g. placeholder={"Enter your email"}
> RegistrationForm/index.tsx and LoginForm/index.tsx should be formatted with tabs.
> <label htmlFor={"name"}>Name
> <input id={"name"} type="text" placeholder={"Enter your name"} required/>
> <label htmlFor={"surname"}>Surname

I think it's prettier when all the attributes are in brackets

2021-08-03 10:59 UTC, kopot-o-d approved these changes

2021-08-03 11:00 UTC, merged