Feature/create post page
BinaryStudioAcademy/bsa-2021-mindbridge pull request #5
Opened 2021-07-31 11:07 UTC by AlenaGavriluk

one new screen CreatePostPage, five new component: createPostForm, header, profileSudebar, historySidebar, logo

2021-08-02 17:25 UTC, nickolay-grechkin commented on frontend/src/screens/CreatePost/containers/CreatePostPage/styles.module.scss
> +.container {
You need to create you screen CreatePost page with grids or set sidebar margin in percents, because  on my resolution inputs and sidebar shifted to the left side.

2021-08-03 07:59 UTC, kopot-o-d reviewed
move ALL SVGs to separate components

2021-08-03 12:03 UTC, Quipex requested changes
Merge with the latest dev to trigger auto-linter

2021-08-04 09:57 UTC, kopot-o-d commented on frontend/src/components/CreatePostForm/CreatePostForm.tsx
> +        <Image1 />
rename it to meaningful name, same with files like svg1 and svg2

2021-08-04 09:58 UTC, kopot-o-d commented on frontend/src/components/CreatePostForm/CreatePostForm.tsx
> +          <Image2 />
same here

2021-08-04 14:52 UTC, kopot-o-d commented on frontend/src/components/PostHistorySidebar/index.tsx
> +    links.push(
don't use .forEach when .map exists

2021-08-04 14:56 UTC, kopot-o-d commented on frontend/src/components/ProfileSidebar/svg/posts.jsx
> +export default function Svg() {
what about name of this function? and there are lots of them in the pull request - check all and rename

2021-08-04 17:02 UTC, merged