added redirect to home page after create post
BinaryStudioAcademy/bsa-2021-mindbridge pull request #50
Opened 2021-08-11 22:49 UTC by Cooplix

2021-08-12 14:28 UTC, kopot-o-d commented on frontend/src/screens/CreatePost/containers/CreatePostPage/index.tsx
> +    history.push('/');
can u change not to main page but to view the created post, like /post/uuid

2021-08-12 21:44 UTC, Quipex requested changes
It's a bad solution. You need to redirect user only on success at saga level when he creates the post. 

Your solution breaks when creating the post fails.

2021-08-16 07:28 UTC, Quipex commented
basically, you need to redirect at saga level

2021-08-16 13:07 UTC, Quipex approved these changes

2021-08-16 13:08 UTC, merged