Feature/create feed page
BinaryStudioAcademy/bsa-2021-mindbridge pull request #9
Opened 2021-08-02 09:21 UTC by nickolay-grechkin

2021-08-02 09:46 UTC, kopot-o-d commented on backend/core/app/src/main/resources/application.properties
> +>>>>>>> Stashed changes
seems like u didn't resolve all merge conflicts

2021-08-03 07:57 UTC, kopot-o-d commented on backend/core/app/src/main/resources/application.properties
> +<<<<<<< Updated upstream
remove

2021-08-03 07:59 UTC, kopot-o-d reviewed
move ALL SVGs to separate components

2021-08-03 12:03 UTC, Quipex requested changes
Merge with the latest dev to trigger auto-linter

2021-08-03 13:12 UTC, nickolay-grechkin commented on frontend/src/screens/FeedPage/routines/index.ts
> +const createFeedPageRoutine = <T extends unknown>(actionName: string) => createRoutine<T>(`FEED_PAGE:${actionName}`);
yes

2021-08-04 08:31 UTC, kopot-o-d approved these changes

2021-08-04 08:32 UTC, kopot-o-d approved these changes

2021-08-04 08:33 UTC, merged